name: Criar Página de Jogo

on:
  workflow_dispatch:
    inputs:
      nome_jogo:
        description: 'Nome do Jogo (Ex: Avakin Mod APK)'
        required: true
        default: ''
      link1:
        description: 'Link do Download 1 (Mediafire, Mega, etc)'
        required: true
        default: ''
      nome2:
        description: 'Nome do Botão 2 (Opcional - Ex: Arquivo OBB)'
        required: false
        default: ''
      link2:
        description: 'Link do Download 2 (Opcional)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerar Página e Exibir Link
        env:
          NOME_JOGO: ${{ github.event.inputs.nome_jogo }}
          LINK1: ${{ github.event.inputs.link1 }}
          NOME2: ${{ github.event.inputs.nome2 }}
          LINK2: ${{ github.event.inputs.link2 }}
          GITHUB_STEP_SUMMARY: ${{ github.step_summary }}
        run: python generate.py

      - name: Salvar no GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          touch .nojekyll
          git add .
          git commit -m "Adicionando jogo ${{ github.event.inputs.nome_jogo }}" || exit 0
          git push
