name: Atualizar Link na Bio

on:
  workflow_dispatch:
    inputs:
      nome_jogo:
        description: 'Nome do Jogo / App (Ex: BitLife BR Mod)'
        required: true
        default: 'Jogo Mod APK'
      link1:
        description: 'Link 1 de Download (Deixe vazio se não usar)'
        required: false
        default: ''
      tag1:
        description: 'Tag do Link 1 (Ex: 64bits, APK, OBB)'
        required: false
        default: '64bits'
      link2:
        description: 'Link 2 de Download (Deixe vazio se não usar)'
        required: false
        default: ''
      tag2:
        description: 'Tag do Link 2 (Ex: 32bits, OBB)'
        required: false
        default: '32bits'
      link3:
        description: 'Link 3 de Download (Deixe vazio se não usar)'
        required: false
        default: ''
      tag3:
        description: 'Tag do Link 3 (Ex: Mod Menu, Outro App)'
        required: false
        default: 'OBB'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerar nova página index.html
        env:
          NOME_JOGO: ${{ github.event.inputs.nome_jogo }}
          LINK1: ${{ github.event.inputs.link1 }}
          TAG1: ${{ github.event.inputs.tag1 }}
          LINK2: ${{ github.event.inputs.link2 }}
          TAG2: ${{ github.event.inputs.tag2 }}
          LINK3: ${{ github.event.inputs.link3 }}
          TAG3: ${{ github.event.inputs.tag3 }}
        run: python generate.py

      - name: Salvar e Publicar alterações
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Atualizando página para: ${{ github.event.inputs.nome_jogo }}" || exit 0
          git push
